repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
            exclude: '\.ambr$'
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-ast
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: mixed-line-ending

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.15.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            args: [--print-width=88, --tab-width=4]
            exclude: |
                (?x)(
                  docs/|
                  PULL_REQUEST_TEMPLATE.md|
                  .github/semantic_release/release_notes.hbs
                )

    - repo: local
      hooks:
          - id: format
            name: format
            description: Runs Code Auto-Formatters
            entry: hatch run lint:fmt
            language: system
            pass_filenames: false
          - id: lint
            name: lint
            description: Runs Code Linters
            entry: hatch run lint:style
            language: system
            pass_filenames: false
            require_serial: false
