name: Publishing

on:
    release:
        types:
            - published

jobs:
    pypi-publish:
        name: PyPI
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch --version
            - name: Build package
              run: |
                  hatch build
            - name: Publish package on PyPI
              uses: pypa/gh-action-pypi-publish@v1.8.10
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_TOKEN }}
