name: Publishing

on:
    release:
        types:
            - published

jobs:
    pypi-publish:
        name: PyPI
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/browsr
        permissions:
            id-token: write
        steps:
            - name: build
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  setup-uv: true
                  task: build
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish package on PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
