name: release
on:
    push:
        branches: [main, next, beta, alpha, "*.x"]
jobs:
    release:
        name: release
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: setup
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  setup-uv: true
                  task: run
                  install: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  args: "echo Beginning..."
            - name: Semantic Release
              uses: juftin/actions/semantic-release@v1
              with:
                  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    docs:
        name: docs
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: build-docs
              uses: juftin/actions/taskfile@v1
              with:
                  checkout: true
                  setup-uv: true
                  task: docs
                  install: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  args: build
            - name: Publish Docs
              uses: juftin/actions/github-pages@v1
              id: deployment
